-- ============================================
-- UDEI Migration 002: New Feature Tables
-- Tables for homework, professor assignments, lecture uploads
-- Also: correct student_payment table definition
-- ============================================

-- ============================================
-- student_payment table (reference definition)
-- This table should already exist. If not, create it:
-- ============================================
CREATE TABLE IF NOT EXISTS public.student_payment (
  id bigint generated by default as identity not null,
  student_id bigint not null,
  amount numeric(12,2) null default 0,
  balance numeric(12,2) null default 0,
  price numeric(12,2) null default 0,
  faculty text null,
  payment_history jsonb null default '[]'::jsonb,
  created_at timestamptz null default now(),
  constraint student_payment_pkey primary key (id),
  constraint student_payment_student_id_fkey foreign key (student_id) references student (id) on delete cascade
) tablespace pg_default;

-- ============================================
-- student_status table (reference definition)
-- Already exists per user's schema. Included for clarity:
-- ============================================
-- create table public.student_status (
--   id bigint generated by default as identity not null,
--   student_id bigint not null,
--   enroll_year date not null,
--   year_study bigint null default '1'::bigint,
--   faculty_completion boolean null,
--   faculty text null,
--   year_commpleted date null,
--   year_completed bigint null default '0'::bigint,
--   academic_year text null,
--   constraint student_status_pkey primary key (id),
--   constraint student_status_student_id_key unique (student_id),
--   constraint student_status_student_id_fkey foreign key (student_id) references student (id) on delete cascade
-- ) tablespace pg_default;

-- ============================================
-- NEW TABLE: homework
-- Stores homework assignments created by professors
-- ============================================
CREATE TABLE IF NOT EXISTS public.homework (
  id bigint generated by default as identity not null,
  title text not null,
  description text null,
  faculty text not null,
  year_study bigint not null default 1,
  matiere text not null,
  due_date date not null,
  created_at timestamptz null default now(),
  created_by uuid null references auth.users(id),
  constraint homework_pkey primary key (id)
) tablespace pg_default;

ALTER TABLE public.homework ENABLE ROW LEVEL SECURITY;

CREATE POLICY "homework_all_staff"
  ON public.homework FOR ALL
  USING (public.get_user_role() IN ('admin', 'administration', 'editor', 'prof'));

CREATE POLICY "homework_select_student"
  ON public.homework FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- ============================================
-- NEW TABLE: homework_submission
-- Tracks student submissions for homework
-- ============================================
CREATE TABLE IF NOT EXISTS public.homework_submission (
  id bigint generated by default as identity not null,
  homework_id bigint not null references public.homework(id) on delete cascade,
  student_id bigint not null references public.student(id) on delete cascade,
  submitted_at timestamptz null default now(),
  grade numeric(5,2) null,
  file_url text null,
  constraint homework_submission_pkey primary key (id),
  constraint homework_submission_unique unique (homework_id, student_id)
) tablespace pg_default;

ALTER TABLE public.homework_submission ENABLE ROW LEVEL SECURITY;

CREATE POLICY "homework_submission_all_staff"
  ON public.homework_submission FOR ALL
  USING (public.get_user_role() IN ('admin', 'administration', 'editor', 'prof'));

CREATE POLICY "homework_submission_select_own"
  ON public.homework_submission FOR SELECT
  USING (
    student_id IN (
      SELECT id FROM student
      WHERE email = public.get_auth_email()
    )
  );

CREATE POLICY "homework_submission_insert_own"
  ON public.homework_submission FOR INSERT
  WITH CHECK (
    student_id IN (
      SELECT id FROM student
      WHERE email = public.get_auth_email()
    )
  );

-- ============================================
-- NEW TABLE: prof_assignment
-- Links professors to their faculty/matière assignments
-- ============================================
CREATE TABLE IF NOT EXISTS public.prof_assignment (
  id bigint generated by default as identity not null,
  prof_id uuid not null references auth.users(id) on delete cascade,
  faculty text not null,
  matiere text not null,
  year_study bigint not null default 1,
  session bigint not null default 1,
  created_at timestamptz null default now(),
  constraint prof_assignment_pkey primary key (id),
  constraint prof_assignment_unique unique (prof_id, faculty, matiere, year_study, session)
) tablespace pg_default;

ALTER TABLE public.prof_assignment ENABLE ROW LEVEL SECURITY;

CREATE POLICY "prof_assignment_all_admin"
  ON public.prof_assignment FOR ALL
  USING (public.get_user_role() IN ('admin', 'administration'));

CREATE POLICY "prof_assignment_select_auth"
  ON public.prof_assignment FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- ============================================
-- NEW TABLE: lecture_upload
-- Stores uploaded lectures, quizzes, and exams
-- ============================================
CREATE TABLE IF NOT EXISTS public.lecture_upload (
  id bigint generated by default as identity not null,
  title text not null,
  file_url text not null,
  faculty text not null,
  matiere text null,
  type text not null default 'lecture' check (type in ('lecture', 'quiz', 'exam')),
  created_at timestamptz null default now(),
  uploaded_by uuid null references auth.users(id),
  constraint lecture_upload_pkey primary key (id)
) tablespace pg_default;

ALTER TABLE public.lecture_upload ENABLE ROW LEVEL SECURITY;

CREATE POLICY "lecture_upload_all_staff"
  ON public.lecture_upload FOR ALL
  USING (public.get_user_role() IN ('admin', 'administration', 'editor', 'prof'));

CREATE POLICY "lecture_upload_select_student"
  ON public.lecture_upload FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- ============================================
-- NEW TABLE: exam_1
-- Session exam results (separate from intra/final in exam table)
-- ============================================
CREATE TABLE IF NOT EXISTS public.exam_1 (
  id bigint generated by default as identity not null,
  student_id bigint not null references public.student(id) on delete cascade,
  matiere text not null,
  note numeric(5,2) null,
  repri_note numeric(5,2) null,
  faculty text null,
  session bigint null,
  year bigint null,
  created_at timestamptz null default now(),
  constraint exam_1_pkey primary key (id)
) tablespace pg_default;

ALTER TABLE public.exam_1 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "exam_1_all_staff"
  ON public.exam_1 FOR ALL
  USING (public.get_user_role() IN ('admin', 'administration', 'editor', 'prof'));

CREATE POLICY "exam_1_select_student"
  ON public.exam_1 FOR SELECT
  USING (
    student_id IN (
      SELECT id FROM student
      WHERE email = public.get_auth_email()
    )
  );

-- ============================================
-- Storage buckets (run these in Supabase Dashboard > Storage)
-- ============================================
-- INSERT INTO storage.buckets (id, name, public) VALUES ('photos', 'photos', true) ON CONFLICT DO NOTHING;
-- INSERT INTO storage.buckets (id, name, public) VALUES ('lectures', 'lectures', true) ON CONFLICT DO NOTHING;
