-- ============================================
-- UDEI Migration 003: Interactive Exam System
-- Tables for online exams with questions, answers, attempts, anti-cheat
-- ============================================

-- ============================================
-- online_exam: Exam definitions created by admin/profs
-- ============================================
CREATE TABLE IF NOT EXISTS public.online_exam (
  id bigint generated by default as identity not null,
  title text not null,
  description text null,
  faculty text not null,
  year_study bigint not null default 1,
  matiere text not null,
  session bigint not null default 1,
  duration_minutes integer not null default 60,
  pass_mark numeric(5,2) not null default 50,
  total_marks numeric(5,2) not null default 100,
  instructions text null,
  is_published boolean not null default false,
  randomize_questions boolean not null default true,
  shuffle_answers boolean not null default true,
  allow_back_nav boolean not null default true,
  max_tab_switches integer not null default 3,
  start_date timestamptz null,
  end_date timestamptz null,
  created_by uuid null references auth.users(id),
  created_at timestamptz null default now(),
  updated_at timestamptz null default now(),
  constraint online_exam_pkey primary key (id)
) tablespace pg_default;

ALTER TABLE public.online_exam ENABLE ROW LEVEL SECURITY;

CREATE POLICY "online_exam_all_staff"
  ON public.online_exam FOR ALL
  USING (public.get_user_role() IN ('admin', 'administration', 'editor', 'prof'));

CREATE POLICY "online_exam_select_student"
  ON public.online_exam FOR SELECT
  USING (auth.uid() IS NOT NULL AND is_published = true);

-- ============================================
-- exam_question: Questions for each exam
-- ============================================
CREATE TABLE IF NOT EXISTS public.exam_question (
  id bigint generated by default as identity not null,
  exam_id bigint not null references public.online_exam(id) on delete cascade,
  question_text text not null,
  question_order integer not null default 0,
  marks numeric(5,2) not null default 1,
  created_at timestamptz null default now(),
  constraint exam_question_pkey primary key (id)
) tablespace pg_default;

ALTER TABLE public.exam_question ENABLE ROW LEVEL SECURITY;

CREATE POLICY "exam_question_all_staff"
  ON public.exam_question FOR ALL
  USING (public.get_user_role() IN ('admin', 'administration', 'editor', 'prof'));

CREATE POLICY "exam_question_select_student"
  ON public.exam_question FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- ============================================
-- exam_answer_option: Answer choices for each question (MCQ)
-- ============================================
CREATE TABLE IF NOT EXISTS public.exam_answer_option (
  id bigint generated by default as identity not null,
  question_id bigint not null references public.exam_question(id) on delete cascade,
  option_text text not null,
  is_correct boolean not null default false,
  option_order integer not null default 0,
  constraint exam_answer_option_pkey primary key (id)
) tablespace pg_default;

ALTER TABLE public.exam_answer_option ENABLE ROW LEVEL SECURITY;

CREATE POLICY "exam_answer_option_all_staff"
  ON public.exam_answer_option FOR ALL
  USING (public.get_user_role() IN ('admin', 'administration', 'editor', 'prof'));

-- Students can read options but NOT see is_correct during exam
-- The client-side should NOT select is_correct for students
CREATE POLICY "exam_answer_option_select_student"
  ON public.exam_answer_option FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- ============================================
-- exam_attempt: Student exam sessions
-- ============================================
CREATE TABLE IF NOT EXISTS public.exam_attempt (
  id bigint generated by default as identity not null,
  exam_id bigint not null references public.online_exam(id) on delete cascade,
  student_id bigint not null references public.student(id) on delete cascade,
  start_time timestamptz not null default now(),
  end_time timestamptz null,
  submitted_at timestamptz null,
  final_score numeric(5,2) null,
  status text not null default 'in_progress' check (status in ('in_progress', 'submitted', 'graded', 'abandoned')),
  tab_switch_count integer not null default 0,
  fullscreen_exit_count integer not null default 0,
  suspicion_score numeric(5,2) not null default 0,
  flagged_for_review boolean not null default false,
  created_at timestamptz null default now(),
  constraint exam_attempt_pkey primary key (id),
  constraint exam_attempt_unique unique (exam_id, student_id)
) tablespace pg_default;

ALTER TABLE public.exam_attempt ENABLE ROW LEVEL SECURITY;

CREATE POLICY "exam_attempt_all_staff"
  ON public.exam_attempt FOR ALL
  USING (public.get_user_role() IN ('admin', 'administration', 'editor', 'prof'));

CREATE POLICY "exam_attempt_select_own"
  ON public.exam_attempt FOR SELECT
  USING (
    student_id IN (
      SELECT id FROM student
      WHERE email = public.get_auth_email()
    )
  );

CREATE POLICY "exam_attempt_insert_own"
  ON public.exam_attempt FOR INSERT
  WITH CHECK (
    student_id IN (
      SELECT id FROM student
      WHERE email = public.get_auth_email()
    )
  );

CREATE POLICY "exam_attempt_update_own"
  ON public.exam_attempt FOR UPDATE
  USING (
    student_id IN (
      SELECT id FROM student
      WHERE email = public.get_auth_email()
    )
  );

-- ============================================
-- exam_attempt_answer: Student's answers per question
-- ============================================
CREATE TABLE IF NOT EXISTS public.exam_attempt_answer (
  id bigint generated by default as identity not null,
  attempt_id bigint not null references public.exam_attempt(id) on delete cascade,
  question_id bigint not null references public.exam_question(id) on delete cascade,
  selected_option_id bigint null references public.exam_answer_option(id) on delete set null,
  is_correct boolean null,
  awarded_marks numeric(5,2) null default 0,
  answered_at timestamptz null default now(),
  constraint exam_attempt_answer_pkey primary key (id),
  constraint exam_attempt_answer_unique unique (attempt_id, question_id)
) tablespace pg_default;

ALTER TABLE public.exam_attempt_answer ENABLE ROW LEVEL SECURITY;

CREATE POLICY "exam_attempt_answer_all_staff"
  ON public.exam_attempt_answer FOR ALL
  USING (public.get_user_role() IN ('admin', 'administration', 'editor', 'prof'));

CREATE POLICY "exam_attempt_answer_select_own"
  ON public.exam_attempt_answer FOR SELECT
  USING (
    attempt_id IN (
      SELECT ea.id FROM exam_attempt ea
      JOIN student s ON s.id = ea.student_id
      WHERE s.email = public.get_auth_email()
    )
  );

CREATE POLICY "exam_attempt_answer_insert_own"
  ON public.exam_attempt_answer FOR INSERT
  WITH CHECK (
    attempt_id IN (
      SELECT ea.id FROM exam_attempt ea
      JOIN student s ON s.id = ea.student_id
      WHERE s.email = public.get_auth_email()
    )
  );

CREATE POLICY "exam_attempt_answer_update_own"
  ON public.exam_attempt_answer FOR UPDATE
  USING (
    attempt_id IN (
      SELECT ea.id FROM exam_attempt ea
      JOIN student s ON s.id = ea.student_id
      WHERE s.email = public.get_auth_email()
    )
  );

-- ============================================
-- exam_event_log: Anti-cheat event tracking
-- ============================================
CREATE TABLE IF NOT EXISTS public.exam_event_log (
  id bigint generated by default as identity not null,
  attempt_id bigint not null references public.exam_attempt(id) on delete cascade,
  event_type text not null check (event_type in ('tab_switch', 'fullscreen_exit', 'copy_paste', 'right_click', 'warning_shown', 'force_submit')),
  severity text not null default 'warning' check (severity in ('info', 'warning', 'critical')),
  details text null,
  created_at timestamptz not null default now(),
  constraint exam_event_log_pkey primary key (id)
) tablespace pg_default;

ALTER TABLE public.exam_event_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "exam_event_log_all_staff"
  ON public.exam_event_log FOR ALL
  USING (public.get_user_role() IN ('admin', 'administration', 'editor', 'prof'));

CREATE POLICY "exam_event_log_insert_own"
  ON public.exam_event_log FOR INSERT
  WITH CHECK (
    attempt_id IN (
      SELECT ea.id FROM exam_attempt ea
      JOIN student s ON s.id = ea.student_id
      WHERE s.email = public.get_auth_email()
    )
  );
